In [25]:
import numpy as np

In [2]:
#Word level one hot encoding

In [3]:
samples = ['Hi I am jinil cs', 'i love machine learning']

In [34]:
word_to_index = {}

In [35]:
for sample in samples:
    words = sample.split()
    for word in words:
        word = word.lower()
        if word not in word_to_index:
            word_to_index[word] = len(word_to_index) + 1

In [36]:
word_to_index

{'am': 3,
 'cs': 5,
 'hi': 1,
 'i': 2,
 'jinil': 4,
 'learning': 8,
 'love': 6,
 'machine': 7}

In [38]:
max_length = 10

In [42]:
one_hot_encoded_samples = np.zeros(
    shape=(len(samples), max_length, max(word_to_index.values())+1))

In [44]:
for i, sample in enumerate(samples):
    for j, word in enumerate(sample.split()):
        word = word.lower()[:max_length]
        if word in word_to_index:
            k = word_to_index[word]
            one_hot_encoded_samples[i,j,k]=1

In [45]:
one_hot_encoded_samples

array([[[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        

In [46]:
#Character Level one hot encoding

In [47]:
import string

In [49]:
chars = string.printable

In [58]:
char_to_index = dict(zip(chars, range(1, len(chars)+1)))

In [61]:
max_length = 50

In [63]:
one_hot_encoded_samples = np.zeros(
    shape=(len(samples), max_length, max(char_to_index.values())+1))

In [64]:
for i, sample in enumerate(samples):
    for j, char in enumerate(sample):
        if char in char_to_index:
            k = char_to_index[char]
            one_hot_encoded_samples[i,j,k] = 1

In [65]:
one_hot_encoded_samples

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]])

In [66]:
#Using Keras word - level one hot encoding

In [2]:
import keras

In [3]:
from keras.preprocessing.text import Tokenizer

In [4]:
samples = ['I am jinil cs.', 'i love machine learning.']

In [5]:
tokenizer = Tokenizer(num_words=1000)

In [6]:
tokenizer.fit_on_texts(samples)

In [7]:
sequences = tokenizer.texts_to_matrix(samples, mode='binary')

In [13]:
tokenizer.word_index

{'am': 2, 'cs': 4, 'i': 1, 'jinil': 3, 'learning': 7, 'love': 5, 'machine': 6}

In [14]:
sequences.shape

(2, 1000)

In [21]:
#using hash

In [23]:
samples = ['I am jinil cs.', 'i love machine learning.']

In [24]:
dimension = 1000
max_length = 10

In [26]:
hashed_samples = np.zeros(shape=(len(samples), max_length, dimension))

for i, sample in enumerate(samples):
    for j, word in enumerate(sample.split()):
        word = word[:max_length]
        index = hash(word) % 1000
        hashed_samples[i,j,index] = 1

In [27]:
hashed_samples

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])